### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by robinnorth**
@rthery I'm taking a look through your fork branches mentioned in #42 and opening PRs where appropriate to try and get some of your helpful work on this project merged in. Hope this is OK!

I'm helping out with maintenance now, so I can action these when they're ready to merge.

### CODE REVIEW

**Comment by rthery** [comment]
@robinnorth No problem at all, feel free to merge what you want. IIRC I tried to have branches for each things, to make it easier to merge if needed ;)
Let me know if you have questions on some stuff!

**Comment by robinnorth** [comment]
@rthery thank you! Your separate branches are indeed very helpful. This particular branch has a merge conflict, would you like to rebase it on master so I can merge? If not, I'll take care of it soon. Cheers!

**Comment by rthery** [comment]
No problem, I resolved the conflict, although I just realized you mentioned rebasing but I merged instead out of habit, I hope it's ok!

**Comment by robinnorth** [comment]
Thank you @rthery, that's great!

**Pull request merged**
